### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by HKrogull** [wylanswets/homebridge-sure-petcare-platform#1]
Hi Wylan,

it is great to see that you started working on the Homebridge integration of Sure PetCare.

When the email and according password I get the error:

TypeError: Cannot read property 'toString' of undefined
    at SurePetcareOccupancySensor.SurePetcareAccessory (/usr/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareAccessory.js:17:81)
    at new SurePetcareOccupancySensor (/usr/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:4:26)
    at SurePetcare.registerOccupancySensor (/usr/lib/node_modules/homebridge-sure-petcare-platform/index.js:138:30)
    at SurePetcare.addPets (/usr/lib/node_modules/homebridge-sure-petcare-platform/index.js:109:14)
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/index.js:48:30
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:112:9
    at SurePetcareApi.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:144:13)
    at Request.self.callback (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

When either is incorrect is tells:

Got an error
{ error: { login: [ 'invalid_email_or_password' ] } }

I still got the device information with the wrong details...

------------------------------------------------
Lock Mechanism |  
-- | --
Lock Current State | 0
Lock Target State | 1
Manufacturer | Sure Petcare
Model | 3
Name | Katzentür
Serial Number | XXXXXXXXXXXXXXXXX
Firmware Revision | MzI0
Homebridge Instance IP | 123.234.456.678
Homebridge Instance Port | 51960
Homebridge Instance Username | 0X:X0:7X:X1:X9:XX
aid | 94
iid | 8
------------------------------------------------------

Might be I'm missing a parameter in my config that is based on the default that you documented.

Great work so far.
Hans

**Comment by wylanswets** [comment]
Hey @HKrogull thanks for reaching out. I apologize for the long delay in getting to this, but I have pushed 2 small changes to how the model info is handled... somehow it thought one of your pets was a lock, so try to update the plugin and see if it starts to work for you. Your login is correct as you thought, that error would only happen after it is pulling data from your account.

Thanks!

**Comment by HKrogull** [comment]
Hi Wylanwets, the change makes the system working as designed.
Thank you. 

Not sure if this is possible, but as the pets are normally inside, the status of occupied should be gray and when cats are outside the status should be red (as it does for the pets when being inside at current). Might be a configuration option to allow flexibility.

I‘m not a developer, but can I help you in getting the curfew mode (scheduled unlock) implemented?!? At current the curfew mode is shown a locked.

Thank you again...

**Comment by wylanswets** [comment]
Hey @HKrogull,

First on the scheduled unlock: what are you looking to implement? As it stands it shows as "Locked" in homekit because that was the clearest to me that the flap was not "open in both directions" and that to some level the pets could not go through it. When in curfew mode it is "locked" to the pet trying to go out, but not in. Inwards direction didn't seem like as big a deal even if it isn't as clear. If that's not what you're talking about let me know!

On the occupancy sensors: I could add an option to flip the state. When I did it initially it seemed simplest that "occupancy detected" meant "inside the house". I do however understand wanting to flip the state to your liking - even if the wording of "occupancy detected" means "outside the house", especially if you made a "back yard room" and put the sensors in there. So yeah, that I can look at adding an option to flip the reporting state - shouldn't be too much of an issue!

**Comment by wylanswets** [comment]
@HKrogull I have pushed an update to the platform. Now the readme describes the "occupancy_flipped" optional variable and how to use it. Hope this helps!

**Comment by HKrogull** [comment]
I hope the 2 mail responses I sent made it.

If not I'll repost here...
