### ISSUE TITLE
lock button unresponsive and incorrect status shown

### ISSUE THREAD

**Issue by kelmk** [wylanswets/homebridge-sure-petcare-platform#13]
The cat door shows up in my Home app as locked even though it is unlocked in the app but when I click on it it just spins trying to unlock forever.

**Comment by kelmk** [comment]
This is what I get in the log


TypeError: Cannot read property 'where' of undefined | stdout

at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:53:42 | stdout

at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:128:56 | stdout

at Array.forEach (<anonymous>) | stdout

at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:128:33 | stdout

at SurePetcareApi.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:165:13) | stdout

at Request.self.callback (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22) | stdout

at Request.emit (events.js:311:20) | stdout

at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10) | stdout

at Request.emit (events.js:311:20) | stdout

at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12) | stdout

at Object.onceWrapper (events.js:417:28) | stdout

at IncomingMessage.emit (events.js:323:22) | stdout

at endReadableNT (_stream_readable.js:1204:12) | stdout

at processTicksAndRejections (internal/process/task_queues.js:84:21) | stdout
-- | --

**Comment by wylanswets** [comment]
Hey @kelmk I have just pushed up 0.1.5 which should resolve this, but it also usually means the pet occupancy can't be found. You can turn off pet occupancy in the config.... with this update it will probably be spitting out an error on the console saying you should turn it off, but also capture the data back from the API... if possible can you send me the output of the error after updating (of course scrub any personal info out of it first too).
