### ISSUE TITLE
homebridge stop running after install Petcare plugin -> acc.pollStatus is not a function

### ISSUE THREAD

**Issue by wunni1** [wylanswets/homebridge-sure-petcare-platform#16]
After installing the plugin the Homebridge stop working, receiving this:

29.10.2020, 14:22:25 error: uncaughtException: acc.pollStatus is not a function date=Thu Oct 29 2020 07:22:25 GMT-0600 (Mountain Daylight Time), pid=12282, uid=1000, gid=1000, cwd=/home/hoobs/.hoobs, execPath=/usr/local/bin/node, version=v12.19.0, argv=[/usr/local/bin/node, /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs, bridge, -u, /home/hoobs/.hoobs/etc, -p, /home/hoobs/.hoobs/node_modules, -r], rss=90099712, heapTotal=27697152, heapUsed=24316284, external=2322144, arrayBuffers=831242, loadavg=[0.12, 0.07, 0.02], uptime=342028
29.10.2020, 14:22:25 TypeError: acc.pollStatus is not a function
29.10.2020, 14:22:25 at /home/hoobs/.hoobs/node_modules/homebridge-sure-petcare-platform/index.js:67:25
29.10.2020, 14:22:25 at /home/hoobs/.hoobs/node_modules/sure_petcare/index.js:134:56
29.10.2020, 14:22:25 at Array.forEach (<anonymous>)
29.10.2020, 14:22:25 at /home/hoobs/.hoobs/node_modules/sure_petcare/index.js:134:33
29.10.2020, 14:22:25 at SurePetcareApi.<anonymous> (/home/hoobs/.hoobs/node_modules/sure_petcare/index.js:171:13)
29.10.2020, 14:22:25 at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
29.10.2020, 14:22:25 at Request.emit (events.js:314:20)
29.10.2020, 14:22:25 at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
29.10.2020, 14:22:25 at Request.emit (events.js:314:20)
29.10.2020, 14:22:25 at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
29.10.2020, 14:22:25 at Object.onceWrapper (events.js:420:28)
29.10.2020, 14:22:25 at IncomingMessage.emit (events.js:326:22)
29.10.2020, 14:22:25 at endReadableNT (_stream_readable.js:1223:12)
29.10.2020, 14:22:25 at processTicksAndRejections (internal/process/task_queues.js:84:21)
29.10.2020, 14:22:25 Got SIGTERM, shutting down Bridge...

**Comment by davidmiller2021** [comment]
I seem to be having the same problem since updating plugins and home bridge to latest versions today.  Can developer fix please?

**Comment by wylanswets** [comment]
Hey guys, are you still getting this error? It's been a while so I'm curious if updates to homebridge have resolved this? Otherwise I'll need to investigate it a bit further.

**Comment by davidmiller2021** [comment]
Hi and thanks for reaching out.

Yes, still getting a problem.

I can send you an error log extract if useful.

David

**Comment by wylanswets** [comment]
Sure, whatever you can send me would be helpful!

I’ll see what I can do to resolve the issue.

**Comment by davidmiller2021** [comment]
I get this in the log - every few minutes

[4/14/2021, 10:18:53 AM] [homebridge-sure-petcare-platform] Loaded homebridge-sure-petcare-platform v0.1.7 child bridge successfully
[4/14/2021, 10:18:53 AM] Loaded 4 cached accessories from cachedAccessories.0EDA29422C6A.
Preparing Advertiser for 'homebridge-sure-petcare-platform FA11' using bonjour-hap backend!
Starting to advertise 'homebridge-sure-petcare-platform FA11' using bonjour-hap backend!
[4/14/2021, 10:18:54 AM] Homebridge v1.3.4 (homebridge-sure-petcare-platform) is running on port 46929.

/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:171
            callback(body);
            ^
TypeError: acc.pollStatus is not a function
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/index.js:67:25
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:56
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:33
    at SurePetcareApi.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:171:13)
    at Request.self.callback (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
[4/14/2021, 10:19:25 AM] [homebridge-sure-petcare-platform] Child bridge process ended
[4/14/2021, 10:19:25 AM] [homebridge-sure-petcare-platform] Process Ended. Code: 1, Signal: null
[4/14/2021, 10:19:32 AM] [homebridge-sure-petcare-platform] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[4/14/2021, 10:19:32 AM] [homebridge-sure-petcare-platform] Launched child bridge with PID 5339
[4/14/2021, 10:19:33 AM] Registering platform 'homebridge-sure-petcare-platform.SurePetcare'
[4/14/2021, 10:19:33 AM] [homebridge-sure-petcare-platform] Loaded homebridge-sure-petcare-platform v0.1.7 child bridge successfully
[4/14/2021, 10:19:33 AM] Loaded 4 cached accessories from cachedAccessories.0EDA29422C6A.

**Comment by hubert3** [comment]
Same thing here, latest plugin with homebridge v1.2.5

It's causing homebridge to restart which is a problem

[5/24/2021, 17:22:25] TypeError: acc.pollStatus is not a function
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/index.js:67:25
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:56
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:33
    at SurePetcareApi.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:171:13)
    at Request.self.callback (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
[5/24/2021, 17:22:25] Got SIGTERM, shutting down Homebridge...

**Comment by hubert3** [comment]
Same crash also happening with homebridge v1.3.4. Have to uninstall for now

**Comment by ab54666** [comment]
Same here.
