### ISSUE TITLE
Keeps Causing Homebridge to restart

### ISSUE THREAD

**Issue by Crox77** [wylanswets/homebridge-sure-petcare-platform#19]
Hi, firstly up until the AWS outage last week, ive had no issues with the Plugin however since then every hour or so the plugin is making HB crash.

Hers is the error message when it crashes.

[11/29/2020, 6:24:10 PM] TypeError: Cannot read property 'data' of null
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:91:27
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:56
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:33
    at SurePetcareApi.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:185:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)

Not sure what's happening, any ideas?

I am running the latest version of the Plugin

Thanks Paul

**Comment by Sommi486** [comment]
I got the same Issue today:

[30/11/2020, 08:53:31] TypeError: Cannot read property 'data' of null
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:46:25
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:56
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:33
    at SurePetcareApi.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:185:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)



I think they have changed their API last week, cause the service had a long offline Time in the night.

I hope the developer will find a solution, cause I like the Plugin very much!!

**Comment by Crox77** [comment]
Yes I love the plug-in very much to as I can lock my cat flap depending on sunset time as I varies by day, I also noticed the last few days it hangs when locking or unlocking and requires a HB restart

**Comment by Sommi486** [comment]
Had somebody contact with the developer?

I really would use this plugin again. 

Please help us!!!!
