### ISSUE TITLE
Homebridge Restart Loop

### ISSUE THREAD

**Issue by akseez** [wylanswets/homebridge-sure-petcare-platform#22]
The plugin is causing Homebridge to go into a restart loop. Everything was working when I added my first pet, but when I added my second pet the issues started. Disabling Pet Occupancy does work around the issue. Do you know when there will be a fix allowing occupancy to be turned on? 

Homebridge v1.3.4
homebridge-sure-petcare-platform v0.1.7 

Here's the excerpt from the log:
 
`TypeError: Cannot read property 'where' of undefined
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:54:33
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:56
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:33
    at SurePetcareApi.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:171:13)
    at Request.self.callback (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)`

**Comment by Sommi486** [comment]
The same happened tonight with my Homebridge! 

@wylanswets could you please help us!

`[27/04/2021, 02:06:17] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Occupancy Detected' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[27/04/2021, 02:06:30] TypeError: Cannot read property 'data' of null
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:91:27
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
[27/04/2021, 02:06:30] Got SIGTERM, shutting down Homebridge...`

**Comment by akseez** [comment]
@wylanswets Are there any updates on this? Thanks!

**Comment by ZoneMR** [comment]
I had this when I added a new pet, with the location not yet being set to indoor or outdoor. 

Worth checking if there are any unused pets registered which could be triggering this?

**Comment by ab54666** [comment]
Same here, real shame as otherwise would be very good.

**Comment by sweidinger** [comment]
Hi,
I tried setting up as an "isolated child bridge", works for me. :-)
<img width="634" alt="Bridge Settings_1" src="https://user-images.githubusercontent.com/10929228/142293248-4b5c5e69-3a9e-40f5-8d88-50d740333244.png">
<img width="804" alt="Bridge Settings_2" src="https://user-images.githubusercontent.com/10929228/142293262-15a785c6-7a82-41ed-aad3-6a38b8fb5e01.png">

**Comment by lieberjott** [comment]
> Hi, I tried setting up as an "isolated child bridge", works for me. :-) 

Can confirm, that this also worked for me. Thanks!
