### ISSUE TITLE
Plugin slowing down Homebridge

### ISSUE THREAD

**Issue by Crox77** [wylanswets/homebridge-sure-petcare-platform#27]
hi I have been getting this error over the last few weeks,

sometimes the locking unlocking hangs and requires a restart of HB but every now and again the plugin is causing HB to crash. 
 
here is a copy of the logs causing the crash

[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Current State' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Target State' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Occupancy Detected' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Occupancy Detected' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Occupancy Detected' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[29/05/2023, 20:45:55] [homebridge-sure-petcare-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Occupancy Detected' was slow to respond! See https://homebridge.io/w/JtMGR for more info.

and also this 

TypeError: Cannot read properties of null (reading 'data')
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:91:27
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:56
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:33
    at SurePetcareApi.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:185:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)

Has anybody else come across this?

Paul

**Comment by Crox77** [comment]
Hi a little update. so today I have come home to work and locking the flap in HK does nothing, I have tried several restarts of Homebridge but this doesn't work, I lock the flap ok in the sure Petcare app but it still shows as unlocked win HK, its almost as if HB plugin is not connecting to the sure Petcare servers, Have they changed their API? any body else having issues today?
Thanks Paul

**Comment by Febus123** [comment]
> Hi a little update. so today I have come home to work and locking the flap in HK does nothing, I have tried several restarts of Homebridge but this doesn't work, I lock the flap ok in the sure Petcare app but it still shows as unlocked win HK, its almost as if HB plugin is not connecting to the sure Petcare servers, Have they changed their API? any body else having issues today? Thanks Paul

Same issue here

**Comment by Crox77** [comment]
> > Hi a little update. so today I have come home to work and locking the flap in HK does nothing, I have tried several restarts of Homebridge but this doesn't work, I lock the flap ok in the sure Petcare app but it still shows as unlocked win HK, its almost as if HB plugin is not connecting to the sure Petcare servers, Have they changed their API? any body else having issues today? Thanks Paul
> 
> Same issue here

Ok so uninstall the plug-in then in stall this one, use the same config as previous plugin 

https://github.com/FrancoisDeBellescize/homebridge-sure-petcare-platform
