### ISSUE TITLE
SIGTERM on Homebridge 1.0.3

### ISSUE THREAD

**Issue by claywd** [wylanswets/homebridge-sure-petcare-platform#5]
The current version is broken in the newest version of homebridge. There aren't a lot of logs output that I could find but if you give me some steps I'll help debug.

`[4/29/2020, 9:13:19 PM] Error: Cannot update reachability on non-bridged accessory!
    at Accessory._this.updateReachability (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:399:13)
    at PlatformAccessory.updateReachability (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge/src/platformAccessory.ts:124:34)
    at new SurePetcarePetFlap (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcarePetFlap.js:19:20)
    at SurePetcare.registerCatFlap (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/index.js:125:30)
    at SurePetcare.addAccessories (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/index.js:92:22)
    at /Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/index.js:41:26
    at /Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:112:9
    at SurePetcareApi.<anonymous> (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:144:13)
    at Request.self.callback (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/Users/clayton/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Comment by wylanswets** [comment]
I personally have not updated to homebridge 1.x yet, what version are you running?

I will have to give the upgrade a go and work through the issues - but a word of warning I would consider staying on the older version if you want an easier experience with all of the existing plugins out there.

Either way I'll work through what I can to resolve the issue!

**Comment by wylanswets** [comment]
So I just pushed out an update for battery status info and upgraded my testing homebridge version to 1.0.4 and I have not gotten this issue, can you make sure you have both up to date and let me know if you still experience the issue?

**Comment by wylanswets** [comment]
Closing due to inactivity... if this is still an issue feel free to re-open this issue. Thanks!
