### ISSUE TITLE
acc.pollStatus is not a function

### ISSUE THREAD

**Issue by kelmk** [wylanswets/homebridge-sure-petcare-platform#6]
[2020-5-3 04:50:47] TypeError: acc.pollStatus is not a function | stdout
at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/index.js:66:21 | stdout
at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:112:9 | stdout
at SurePetcareApi.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:144:13) | stdout
at Request.self.callback (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22) | stdout
at Request.emit (events.js:180:13) | stdout
at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10) | stdout
at Request.emit (events.js:180:13) | stdout
at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12) | stdout
[2020-5-3 04:50:47] Got SIGTERM, shutting down Homebridge...

at Object.onceWrapper (events.js:272:13) | stdout
-- | --

at IncomingMessage.emit (events.js:185:15) | stdout
-- | --

at endReadableNT (_stream_readable.js:1101:12) | stdout
-- | --

at process._tickCallback (internal/process/next_tick.js:114:19) | stdout
-- | --

[2020-5-3 04:50:47] Got SIGTERM, shutting down Homebridge...

**Comment by wylanswets** [comment]
What version of homebridge are you running?

**Comment by kelmk** [comment]
Not sure what I was on before but I just updated to 1.0.4 to check. Same error.

**Comment by kelmk** [comment]
I just updated my doctor container to the latest image and redownloaded all my plugins. Same error :/

**Comment by kelmk** [comment]
Just tried installing the latest oznu/homebridge docker container for fun and no luck. I was using marcoraddatz-homebridge before.  Same error either way.
acc.pollStatus is not a function 
Thanks for your help

**Comment by wylanswets** [comment]
What version of the plugin are you running? I just released an unrelated update to support battery info - but just want to be sure we're troubleshooting the same version.

**Comment by wylanswets** [comment]
Also, I just upgraded my testing setup to homebridge 1.0.4 (latest as of writing) and am not getting that issue, so that rules out the newest homebridge being an issue (at least for now).

**Comment by kelmk** [comment]
Looks like 1.2. I just uninstalled and reinstalled to make sure I'm using the latest.

Strangely I'm now getting this error :/

[5/8/2020, 10:42:25 AM] TypeError: Cannot read property 'where' of undefined | stdout
at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:53:42 | stdout

**Comment by LeviJSmith** [comment]
I’m getting this error as well now.  Not sure why.  It worked fine then today I restarted Homebridge and am now getting the Acc poll status error.

**Comment by LeviJSmith** [comment]
Just upgraded to Hoobs 3.2.4 and the Sure plugin is working again.

**Comment by wylanswets** [comment]
Closing due to inactivity. If this is still an issue please feel free to re-open this issue. Thanks!
