### ISSUE TITLE
SIGTERM on homebridge v4.28.0

### ISSUE THREAD

**Issue by deenice87** [wylanswets/homebridge-sure-petcare-platform#9]
Hi there, i have the same know Issue with homebridge v4.28.0

`TypeError: Cannot read property 'where' of undefined
    at /homebridge/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:53:42
    at /homebridge/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:128:56
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:128:33
    at SurePetcareApi.<anonymous> (/homebridge/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:165:13)
    at Request.self.callback (/homebridge/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)`

Homebridge gets SIGTERM and restarts.

Is there any way i could fix this?

Thanks in advance!

**Comment by wylanswets** [comment]
Hey @deenice87! I just looked in to this, it appears that the "Pet occupancy" is causing the issue. I'm not exactly sure why that would be occurring, but you could try first turning off the "pet_occupancy" feature in config and see if it will run.

If you would like pet occupancy working I will need to dig in further, but please give that a try and see if that works.

Thanks!

**Comment by deenice87** [comment]
Hi @wylanswets - thank you for your response! To be honest - i am not a coder and really dont have a clue where i could find and change these code lines. If you could give me a little hint - would be amazing! Thanks in advance, greetings Dennis

**Comment by wylanswets** [comment]
Hey @deenice87 no problem! So in the configuration of this plugin (what you put in your homebridge config.json file), there's the option called "pet_occupancy" which is set to true. Change it so that line reads:

"pet_occupancy": false,

That should disable that feature and we can see what happens from there.

**Comment by deenice87** [comment]
seems to work! Thank you very much! No further errors 👍 :-)

**Comment by wylanswets** [comment]
Great! If you do want pet occupancy working let me know I can look further in to it. I’m not sure if your pets don’t do indoor/outdoor detection or what is going on there but I’d probably need temporary access to your sure Petcare account (via invite) to figure that out. Again that’s if you want occupancy.

Let me know, but glad we could get you up and running!

**Comment by wylanswets** [comment]
0.1.5 should fix this issue if you have sensors enabled and it cannot be detected. It won't make it work, but will give you an error message on the console suggesting you turn it off. Until I can find out why this is happening this is probably the best fix.

**Comment by akseez** [comment]
@wylanswets 
I am also experiencing this issue with: 
Homebridge v1.3.4
homebridge-sure-petcare-platform v0.1.7 

Disabling Pet Occupancy does work around the issue. Do you know when there will be a fix allowing occupancy to be turned on? 

Here's the excerpt from the log: 
`TypeError: Cannot read property 'where' of undefined
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:54:33
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:56
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:134:33
    at SurePetcareApi.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:171:13)
    at Request.self.callback (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)`
